In [1]:
import numpy as np
import pandas as pd

print(f"pandas 版本: {pd.__version__}")
print(f"numpy 版本: {np.__version__}")
print("✅ pandas 环境就绪，开始学习！")

pandas 版本: 3.0.2
numpy 版本: 2.4.4
✅ pandas 环境就绪，开始学习！

In [82]:
## 1. Series 基础
obj=pd.Series([4,7-5,3])
obj

0    4
1    2
2    3
dtype: int64

In [83]:
obj.values

array([4, 2, 3])

In [84]:
obj.index

RangeIndex(start=0, stop=3, step=1)

In [85]:
obj2=pd.Series([4,7,-5,3],index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [86]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='str')

In [87]:
obj2.values

array([ 4,  7, -5,  3])

In [88]:
obj2['a']

np.int64(-5)

In [89]:
obj2['d']=6
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [90]:
obj2[obj2<0]

a   -5
dtype: int64

In [91]:
obj2*5

d    30
b    35
a   -25
c    15
dtype: int64

In [92]:
'b' in obj2

True

In [93]:
'e' in obj2

False

In [94]:
sdata = {"beijing": 50000, "shanghai": 45000, "guangzhou": 40000, "shenzhen": 60000}
obj3 = pd.Series(sdata)
obj3

beijing      50000
shanghai     45000
guangzhou    40000
shenzhen     60000
dtype: int64

In [95]:
states=['chengdu','beijing','shanghai','shenzhen']
obj4=pd.Series(sdata,index=states)
obj4

chengdu         NaN
beijing     50000.0
shanghai    45000.0
shenzhen    60000.0
dtype: float64

In [96]:
pd.isnull(obj3)

beijing      False
shanghai     False
guangzhou    False
shenzhen     False
dtype: bool

In [97]:
pd.notnull(obj4)

chengdu     False
beijing      True
shanghai     True
shenzhen     True
dtype: bool

In [98]:
obj4.isnull

<bound method Series.isnull of chengdu         NaN
beijing     50000.0
shanghai    45000.0
shenzhen    60000.0
dtype: float64>

In [99]:
obj3+obj4

beijing      100000.0
chengdu           NaN
guangzhou         NaN
shanghai      90000.0
shenzhen     120000.0
dtype: float64

In [100]:
obj4.name='house price'
obj4.index.name='city'
obj4

city
chengdu         NaN
beijing     50000.0
shanghai    45000.0
shenzhen    60000.0
Name: house price, dtype: float64

In [101]:
obj3

beijing      50000
shanghai     45000
guangzhou    40000
shenzhen     60000
dtype: int64

In [102]:
obj4

city
chengdu         NaN
beijing     50000.0
shanghai    45000.0
shenzhen    60000.0
Name: house price, dtype: float64

In [103]:
obj.index=['a','b','d']
obj

a    4
b    2
d    3
dtype: int64

## 2.Dataframe 基础

In [104]:
data={'city':['beijing','shanghai','guangzhou','shenzhen','chengdu'],'year':[2000,2001,2002,2003,2005],'pop':[1.5,1.8,2.2,1.9,2]}
frame=pd.DataFrame(data)
frame

        city  year  pop
0    beijing  2000  1.5
1   shanghai  2001  1.8
2  guangzhou  2002  2.2
3   shenzhen  2003  1.9
4    chengdu  2005  2.0

In [105]:
data={'city':['beijing','shanghai','guangzhou','shenzhen','chengdu','chongqing'],'year':[2000,2001,2002,2003,2004,2006],'pop':[1.5,2,2.1,1.9,2,2.5]}
frame=pd.DataFrame(data)
frame

        city  year  pop
0    beijing  2000  1.5
1   shanghai  2001  2.0
2  guangzhou  2002  2.1
3   shenzhen  2003  1.9
4    chengdu  2004  2.0
5  chongqing  2006  2.5

In [106]:
frame.head()

        city  year  pop
0    beijing  2000  1.5
1   shanghai  2001  2.0
2  guangzhou  2002  2.1
3   shenzhen  2003  1.9
4    chengdu  2004  2.0

In [107]:
pd.DataFrame(data,columns=['year','pop','city'])

   year  pop       city
0  2000  1.5    beijing
1  2001  2.0   shanghai
2  2002  2.1  guangzhou
3  2003  1.9   shenzhen
4  2004  2.0    chengdu
5  2006  2.5  chongqing

In [108]:
frame2=pd.DataFrame(data,columns=['year','city','pop','debt'],index=['one','two','three','four','five','six'])
frame2

       year       city  pop debt
one    2000    beijing  1.5  NaN
two    2001   shanghai  2.0  NaN
three  2002  guangzhou  2.1  NaN
four   2003   shenzhen  1.9  NaN
five   2004    chengdu  2.0  NaN
six    2006  chongqing  2.5  NaN

In [109]:
frame2['city']

one        beijing
two       shanghai
three    guangzhou
four      shenzhen
five       chengdu
six      chongqing
Name: city, dtype: str

In [110]:
frame2.loc['two']

year        2001
city    shanghai
pop          2.0
debt         NaN
Name: two, dtype: object

In [111]:
frame2['debt']=15
frame2

       year       city  pop  debt
one    2000    beijing  1.5    15
two    2001   shanghai  2.0    15
three  2002  guangzhou  2.1    15
four   2003   shenzhen  1.9    15
five   2004    chengdu  2.0    15
six    2006  chongqing  2.5    15

In [112]:
val=pd.Series([-1.2,-1.5,-1.9],index=['one','two','three'])
frame2['debt']=val
frame2

       year       city  pop  debt
one    2000    beijing  1.5  -1.2
two    2001   shanghai  2.0  -1.5
three  2002  guangzhou  2.1  -1.9
four   2003   shenzhen  1.9   NaN
five   2004    chengdu  2.0   NaN
six    2006  chongqing  2.5   NaN

In [113]:
frame2['bule']=frame2.pop==2.0
frame2

       year       city  pop  debt   bule
one    2000    beijing  1.5  -1.2  False
two    2001   shanghai  2.0  -1.5  False
three  2002  guangzhou  2.1  -1.9  False
four   2003   shenzhen  1.9   NaN  False
five   2004    chengdu  2.0   NaN  False
six    2006  chongqing  2.5   NaN  False

In [114]:
del frame2['bule']
frame2

       year       city  pop  debt
one    2000    beijing  1.5  -1.2
two    2001   shanghai  2.0  -1.5
three  2002  guangzhou  2.1  -1.9
four   2003   shenzhen  1.9   NaN
five   2004    chengdu  2.0   NaN
six    2006  chongqing  2.5   NaN

In [115]:
pop={'beijing':{2001:2,2002:2.6},'shanghai':{2000:1.9,2001:2.2,2002:2.6}}
frame3=pd.DataFrame(pop)
frame3

      beijing  shanghai
2001      2.0       2.2
2002      2.6       2.6
2000      NaN       1.9

In [116]:
frame3.T

          2001  2002  2000
beijing    2.0   2.6   NaN
shanghai   2.2   2.6   1.9

In [117]:
frame3.index.name='year'
frame3.columns.name='city'
frame3

city  beijing  shanghai
year
2001      2.0       2.2
2002      2.6       2.6
2000      NaN       1.9

## 3.loc/iloc/布尔索引

In [118]:
print("---loc['two']---")
print(frame2.loc['two'])

---loc['two']---
year        2001
city    shanghai
pop          2.0
debt        -1.5
Name: two, dtype: object

In [119]:
print("\n---iloc[1]---")
print(frame2.iloc[1])

---iloc[1]---
year        2001
city    shanghai
pop          2.0
debt        -1.5
Name: two, dtype: object

In [120]:
print(frame2.loc['two', ['year', 'pop']])

year    2001.0
pop        2.0
Name: two, dtype: float64

In [121]:
print(frame2.iloc[1, [0, 2]])

year    2001.0
pop        2.0
Name: two, dtype: float64

In [125]:
print(frame2.iloc[[0,2],1])

one        beijing
three    guangzhou
Name: city, dtype: str

In [126]:
print(frame2[frame2['pop'] > 2])

       year       city  pop  debt
three  2002  guangzhou  2.1  -1.9
six    2006  chongqing  2.5   NaN

In [127]:
print(frame2[(frame2['pop'] > 2) & (frame2['year'] > 2001)])

       year       city  pop  debt
three  2002  guangzhou  2.1  -1.9
six    2006  chongqing  2.5   NaN

In [128]:
frame2.loc[frame2['pop'] > 2, ['city', 'year']]

            city  year
three  guangzhou  2002
six    chongqing  2006